;/*FB_PKG_DELIM*/

__d("CometFileSelector.react",["react","recoverableViolation"],(function(a,b,c,d,e,f,g){"use strict";var h,i=h||(h=d("react"));b=h;var j=b.useCallback,k=b.useEffect,l=b.useRef;function m(a){return a.map(function(a){if(a.indexOf("/")!==-1||a[0]===".")return a;c("recoverableViolation")('Accept parameter "'+a+'" for CometFileSelector is being interpreted as a file extension since it has no slash (/), but file extensions must start with a period (.)',"profile_comet");return"."+a}).join(",")}function a(a){var b=a.accept,c=a.children,d=a.multiple;d=d===void 0?!1:d;var e=a.onFilesSelected,f=l(null);k(function(){var a=f.current;if(a!=null){var b=function(a){a.stopPropagation()};a.addEventListener("click",b);return function(){a.removeEventListener("click",b)}}});a=j(function(){f.current!=null&&f.current.click()},[]);var g=j(function(a){e(a.currentTarget.files),a.currentTarget.value=""},[e]);b=i.jsxs(i.Fragment,{children:[i.jsx("input",{accept:b!=null?m(b):void 0,className:"x1s85apg",multiple:d,onChange:g,ref:f,type:"file"}),c(a)]});return b}g["default"]=a}),98);
__d("useFileDragEvents",["react"],(function(a,b,c,d,e,f,g){"use strict";var h;b=h||d("react");var i=b.useCallback,j=b.useEffect,k=b.useRef,l=b.useState;function a(a,b,c){b===void 0&&(b=document.documentElement);var d=k(0),e=l(!1),f=e[0],g=e[1],h=i(function(b){g(!1);if((c==null||c(b))&&a!=null){b.preventDefault();var e=b.dataTransfer;if(e!=null){e=e.files;a(e,b)!==!1&&b.stopPropagation()}else b.stopPropagation();d.current=0}},[a,c]),m=i(function(a){var b;b=(b=a.dataTransfer)==null?void 0:b.files;(c==null||c(a))&&b!=null&&(a.preventDefault(),d.current++,g(!0))},[c]),n=i(function(a){var b;b=(b=a.dataTransfer)==null?void 0:b.files;(c==null||c(a))&&b!=null&&--d.current===0&&g(!1)},[c]),o=i(function(a){var b;b=(b=a.dataTransfer)==null?void 0:b.files;b!=null&&a.preventDefault()},[]);j(function(){if(b!=null){b.addEventListener("drop",h,!0);b.addEventListener("dragenter",m,!0);b.addEventListener("dragleave",n,!0);b.addEventListener("dragover",o,!0);return function(){b.removeEventListener("drop",h,!0),b.removeEventListener("dragenter",m,!0),b.removeEventListener("dragleave",n,!0),b.removeEventListener("dragover",o,!0)}}},[m,n,o,h,b]);return f}g["default"]=a}),98);
__d("fileInputAcceptValues",[],(function(a,b,c,d,e,f){"use strict";a=[".png",".jpg",".jpeg"];b=["image/*","image/heif","image/heic"];c=["video/*","video/mp4","video/x-m4v","video/x-matroska",".mkv"];d=b.concat(c);f.CUSTOM_THUMBNAIL=a;f.PHOTO=b;f.VIDEO=c;f.PHOTO_AND_VIDEO=d}),66);
__d("CometTypeaheadViewList.react",["CometCompositeStructureContext","getItemRoleFromCompositeRole","react"],(function(a,b,c,d,e,f,g){"use strict";var h,i=h||(h=d("react")),j=h.useMemo;function a(a){var b=a.ariaProps,d=a.children,e=a.entries,f=a.highlightedEntry;a=babelHelpers.objectWithoutPropertiesLoose(a,["ariaProps","children","entries","highlightedEntry"]);var g=f!=null?f.key:null,h=b.role;a=j(function(){if(h!=null)return{role:h};else return{}},[h]);var k=c("getItemRoleFromCompositeRole")(h);return e!=null&&e.length>0?i.jsx("ul",babelHelpers["extends"]({},b,{className:"x78zum5 xdt5ytf x1iyjqo2","data-testid":void 0,children:i.jsx(c("CometCompositeStructureContext").Provider,{value:a,children:e.map(function(a,b){var c=g===a.key;return d({entry:a,index:b,isActive:c,itemRole:k})})})})):null}a.displayName=a.name+" [from "+f.id+"]";g["default"]=a}),98);
__d("CometTypeaheadViewListStrategy.react",["CometTypeaheadViewList.react","react"],(function(a,b,c,d,e,f,g){"use strict";var h,i=h||d("react");function a(a){var b=a.ariaProps,d=a.entries;a.extraViewProps;var e=a.highlightedEntry;a.isLoading;a.onAbandonTypeahead_DO_NOT_USE;var f=a.viewItemStrategyRenderer,g=babelHelpers.objectWithoutPropertiesLoose(a,["ariaProps","entries","extraViewProps","highlightedEntry","isLoading","onAbandonTypeahead_DO_NOT_USE","viewItemStrategyRenderer"]);return i.jsx(c("CometTypeaheadViewList.react"),{ariaProps:b,entries:d,highlightedEntry:e,testid:void 0,children:function(a){var b=a.entry,c=a.isActive;a=a.itemRole;return i.createElement(f,babelHelpers["extends"]({},g,{entry:b,isActive:c,key:b.key,role:a}))}})}a.displayName=a.name+" [from "+f.id+"]";g["default"]=a}),98);
__d("useCometTypeaheadViewListStrategy",["CometTypeaheadProgressGlimmer.react","CometTypeaheadViewListStrategy.react","react","stylex"],(function(a,b,c,d,e,f,g){"use strict";var h,i,j=i||(i=d("react")),k=i.useCallback;function a(a){var b=a.emptyStateContent,d=a.extraViewProps,e=a.nullstateContent,f=a.viewItemStrategyRenderer,g=a.viewListStrategyRenderer,i=g===void 0?c("CometTypeaheadViewListStrategy.react"):g,l=a.viewXStyle;return k(function(a){var g=a.entries,k=a.isLoading,m=a.queryString;a=babelHelpers.objectWithoutPropertiesLoose(a,["entries","isLoading","queryString"]);if(m.length===0&&e!=null)return e;return g.length===0&&b!=null?b:j.jsxs("div",{className:(h||(h=c("stylex")))([l]),children:[j.jsx(i,babelHelpers["extends"]({},a,{entries:g,extraViewProps:d,isLoading:!1,queryString:m,viewItemStrategyRenderer:f})),k&&j.jsx(c("CometTypeaheadProgressGlimmer.react"),{})]})},[i,b,d,e,f,l])}g["default"]=a}),98);
__d("makeImmutable",[],(function(a,b,c,d,e,f){"use strict";function a(a){throw new Error("This empty "+((a=a)!=null?a:"Object")+" cannot be mutated.")}function b(a,b){return a}f["default"]=b}),66);
__d("emptyArray",["makeImmutable"],(function(a,b,c,d,e,f,g){"use strict";a=c("makeImmutable")([],["copyWithin","fill","pop","push","reverse","shift","sort","splice","unshift"]);b=a;g["default"]=b}),98);
__d("firstKeyWithValue",[],(function(a,b,c,d,e,f){"use strict";function a(a,b){for(var c in a){var d=c;if(Object.prototype.hasOwnProperty.call(a,d)&&a[d]===b)return d}return null}f["default"]=a}),66);
__d("castToEnum",[],(function(a,b,c,d,e,f){"use strict";function a(a,b,c){var d=Object.keys(b);for(var e=0;e<d.length;e++)if(b[d[e]]===a)return b[d[e]];return c}f["default"]=a}),66);
__d("goURIOnWindow",["ConstUriUtils","FBLogger","err"],(function(a,b,c,d,e,f,g){"use strict";function a(a,b){var e=typeof b==="string"?d("ConstUriUtils").getUri(b):d("ConstUriUtils").isConstUri(b);if(e){if(a==null)return!1;a.location=e.toString();return!0}else{a="Invalid URI "+b.toString()+" provided to goURIOnWindow";c("FBLogger")("comet_infra").blameToPreviousFrame().mustfix(a);return!1}}g["default"]=a}),98);
__d("goUriOnNewWindow",["goURIOnWindow"],(function(a,b,c,d,e,f,g){"use strict";function a(a){var b=window.open("","_blank");return b==null?!1:c("goURIOnWindow")(b,a)}g["default"]=a}),98);
__d("BaseTypeaheadBaseStaticDataSource",["BaseTypeaheadDataCacheProvider","BaseTypeaheadInMemoryMapDataCache","baseTypeaheadStartsWithMatchBuilder"],(function(a,b,c,d,e,f,g){"use strict";a=function(){function a(a){var b=a.entries,d=a.keyBuilder;a=a.matchBuilder;a=a===void 0?c("baseTypeaheadStartsWithMatchBuilder"):a;this.$1=new(c("BaseTypeaheadDataCacheProvider"))({cache:new(c("BaseTypeaheadInMemoryMapDataCache"))(),keyBuilder:d,matchBuilder:a});this.$1.add(b)}var b=a.prototype;b.fetchCache=function(a){var b=a.query;return{entries:this.$1.match(b),params:a}};return a}();g["default"]=a}),98);